### ISSUE TITLE
Remove Python Logic and keep views

### ISSUE THREAD

**Issue by sbuhl** [sbuhl/account_approval#2]
Rationale: le système mis en place ralenti les opérations. Le système par défaut d'Odoo est suffisant.

Specification:
- Enlever la logique python (sécurité et model) 
- Garder que la vue [account_approval_request_inherited_tree.xml]
     - attention la vue peut avoir été modifiée sur la prod via studio, il faut ajouter les éléments de studio dans la vue custo 
- des attachements ont été ajoutés sur les bank.statement.line, 
    - les déplacer sur les bank.statement correspondants

**Comment by shortcut1337** [comment]
Done with https://github.com/sbuhl/account_approval/pull/3
