### ISSUE TITLE
Duplicate a quotation/order, remove the discounts

### ISSUE THREAD

**Issue by sbuhl** [sbuhl/account_approval#7]
If a quotation has discounts and one duplicates it, discounts are also duplicated.
Due to our custo, if one duplicates an order with discount above its access rights, 
a message prevent him to do so. 
We should either let him duplicate it, and check the access rights on the save
either remove all the discounts on a duplicate.
The latter option is the worse...

**Comment by shortcut1337** [comment]
Fix at https://github.com/sbuhl/account_approval/pull/8
